import time


print('=' * 30)
print("A", end='')
time.sleep(0.2)
print("R", end='')
time.sleep(0.2)
print("E", end='')
time.sleep(0.2)
print("N", end='')
time.sleep(0.2)
print("A", end='')
time.sleep(0.2)
print(" S", end='')
time.sleep(0.2)
print("O", end='')
time.sleep(0.2)
print("M", end='')
time.sleep(0.2)
print("O", end='')
time.sleep(0.2)
print("S", end='')
time.sleep(0.2)
print(" U", end='')
time.sleep(0.3)
print("M", end='')
